In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import accuracy_score

In [3]:
df=pd.read_csv(r"C:\Users\User\OneDrive\Desktop\python\email-spam.csv")

In [4]:
df.head()

,email_id,subject,email_text,sender_email,sender_domain,label
0,0,Weekly Report,budget review - Statement our I claim world st...,lctvdzm@outlook.com,outlook.com,0
1,1,Project Update,team sync - President series today already. In...,pxyldmi@company.com,company.com,0
2,2,🔥WIN BIG NOW!!,win free urgent offer limited limited urgent u...,atvanls@unknownmail.cc,unknownmail.cc,1
3,3,🔥WIN BIG NOW!!,guarantee click now cash offer click now guara...,qalxcnf@chealdealz.xyz,chealdealz.xyz,1
4,4,Meeting Reminder,team sync - Significant property hotel not add...,xoiccxl@yahoo.com,yahoo.com,0

In [5]:
df.drop(['email_id', 'subject', 'sender_email', 'sender_domain'],axis=1,inplace=True)

In [6]:
df

                                             email_text  label
0     budget review - Statement our I claim world st...      0
1     team sync - President series today already. In...      0
2     win free urgent offer limited limited urgent u...      1
3     guarantee click now cash offer click now guara...      1
4     team sync - Significant property hotel not add...      0
...                                                 ...    ...
9995  free win cash win guarantee urgent free win li...      1
9996  click now free guarantee free win click now wi...      1
9997  offer cash win limited click now cash limited ...      1
9998           budget review - Many result affect idea.      0
9999  budget review - Day measure few alone decade a...      0

[10000 rows x 2 columns]

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   email_text  10000 non-null  str
 1   label       10000 non-null  int64
dtypes: int64(1), str(1)
memory usage: 156.4 KB

In [8]:
df.isnull().sum()

email_text    0
label         0
dtype: int64

In [9]:
X = df['email_text']
y = df['label']

In [10]:
X

0       budget review - Statement our I claim world st...
1       team sync - President series today already. In...
2       win free urgent offer limited limited urgent u...
3       guarantee click now cash offer click now guara...
4       team sync - Significant property hotel not add...
                              ...
9995    free win cash win guarantee urgent free win li...
9996    click now free guarantee free win click now wi...
9997    offer cash win limited click now cash limited ...
9998             budget review - Many result affect idea.
9999    budget review - Day measure few alone decade a...
Name: email_text, Length: 10000, dtype: str

In [11]:
y

0       0
1       0
2       1
3       1
4       0
       ..
9995    1
9996    1
9997    1
9998    0
9999    0
Name: label, Length: 10000, dtype: int64

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [13]:
X_train

9254    limited free free offer cash limited win click...
1561    schedule - Here possible nice gas top instead ...
1670    project update - Attention attorney writer qui...
6087    urgent guarantee click now win offer urgent ca...
6669    win guarantee win offer guarantee free win cas...
                              ...
5734    meeting - Real poor table sport other huge dra...
5191    schedule - Half guess approach point training ...
5390    budget review - Beat industry dog performance ...
860     click now limited urgent offer free free guara...
7270    budget review - Black that free social these. ...
Name: email_text, Length: 8000, dtype: str

In [14]:
y_train

9254    1
1561    0
1670    0
6087    1
6669    1
       ..
5734    0
5191    0
5390    0
860     1
7270    0
Name: label, Length: 8000, dtype: int64

In [15]:
ve=CountVectorizer()
X_train = ve.fit_transform(X_train)
X_test = ve.transform(X_test)

In [16]:
X_test

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 30762 stored elements and shape (2000, 978)>

In [17]:
m=MultinomialNB()
m.fit(X_train,y_train)

MultinomialNB()

In [18]:
pred = m.predict(X_test)

In [19]:
print(pred)

[1 0 1 ... 1 1 0]

In [20]:
print("accuracy score::", accuracy_score(y_test,pred))

accuracy score:: 1.0

In [29]:
test = [
    "Limited Offer!!!"
]

new_ve = ve.transform(test)
y_pred = m.predict(new_ve)
print("prediction: ", y_pred)

prediction:  [1]